name: Deploy to EKS

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: target

      - name: Build Docker image
        run: |
          docker build -t 841162698708.dkr.ecr.us-east-1.amazonaws.com/ms-product .

      - name: Install and configure AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 841162698708.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag and push Docker image
        run: |
          docker push 841162698708.dkr.ecr.us-east-1.amazonaws.com/ms-product:${GITHUB_SHA}

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-cluster-aws-fiap

          mkdir -p k8s
          export ECR_REPOSITORY_URL="841162698708.dkr.ecr.us-east-1.amazonaws.com/ms-product:${GITHUB_SHA}"
          envsubst < kubernetes/producao/k8s-deployment.yaml > k8s/k8s-deployment.yaml
          echo "resources:" > k8s/kustomization.yaml
          echo "- k8s-deployment.yaml" >> k8s/kustomization.yaml
          kubectl kustomize k8s | kubectl apply -f - --force
